const colecaoUf = [
    { id: 1, uf: "AC", nome: "Acre" },
    { id: 2, uf: "AL", nome: "Alagoas" },
    { id: 3, uf: "AP", nome: "Amapa" },
    { id: 4, uf: "AM", nome: "Amazonas" },
    { id: 5, uf: "BA", nome: "Bahia" },
    { id: 6, uf: "CE", nome: "Ceara" },
    { id: 7, uf: "DF", nome: "Distrito Federal" },
    { id: 8, uf: "ES", nome: "Espirito Santo" },
    { id: 9, uf: "GO", nome: "Goias" },
    { id: 10, uf: "MA", nome: "Maranhao" },
    { id: 11, uf: "MT", nome: "Mato Grosso" },
    { id: 12, uf: "MS", nome: "Mato Grosso do Sul" },
    { id: 13, uf: "MG", nome: "Minas Gerais" },
    { id: 14, uf: "PA", nome: "Para" },
    { id: 15, uf: "PB", nome: "Paraiba" },
    { id: 16, uf: "PR", nome: "Parana" },
    { id: 17, uf: "PE", nome: "Pernambuco" },
    { id: 18, uf: "PI", nome: "Piaui" },
    { id: 19, uf: "RJ", nome: "Rio de Janeiro" },
    { id: 20, uf: "RN", nome: "Rio Grande do Norte" },
    { id: 21, uf: "RS", nome: "Rio Grande do Sul" },
    { id: 22, uf: "RO", nome: "Rondonia" },
    { id: 23, uf: "RR", nome: "Roraima" },
    { id: 24, uf: "SC", nome: "Santa Catarina" },
    { id: 25, uf: "SP", nome: "Sao Paulo" },
    { id: 26, uf: "SE", nome: "Sergipe" },
    { id: 27, uf: "TO", nome: "Tocantins" }
];

export default colecaoUf;
